### ISSUE TITLE
Can't open Office Documents on NC 26.0.1, Office 8.0.1

### ISSUE THREAD

**Issue by mnheia** [nextcloud/richdocuments#2942]
**Describe the bug**

Office through Nextcloud App on mobile doesn't work. It works in a browser but not in an app. Tried with several different phones with everything updated to the latest version. 

I believe this is related to #2873 and or maybe #2874 which are closed and should be resolved.

**Screenshots**

<a href='https://postimg.cc/SXWDTQs4' target='_blank'><img src='https://i.postimg.cc/SXWDTQs4/Screenshot-2023-05-10-12-19-17-83-06ea656a9ba653ff96746f477f32d0f9.jpg' border='0' alt='Screenshot-2023-05-10-12-19-17-83-06ea656a9ba653ff96746f477f32d0f9'/></a>

**Client details:**
- Android 13, Pixel 6 Pro, OnePlus 10 Pro 5G, ...

## Server details
- Nextcloud 26.0.1
- Nextcloud Office 8.0.1 
- Collabora 22.05.14.3
- Nextcloud Client 26.0.1.1
- 
#### Apache configuration 
Only part for the Collabora

```
        # Encoded slashes need to be allowed
        AllowEncodedSlashes NoDecode

        # Container uses a unique non-signed certificate
        SSLProxyEngine On
        SSLProxyVerify None
        SSLProxyCheckPeerCN Off
        SSLProxyCheckPeerName Off

        # keep the host
        ProxyPreserveHost On

        # static html, js, images, etc. served from coolwsd
        # browser is the client part of LibreOffice Online
        ProxyPass           /browser https://127.0.0.1:9980/browser retry=0
        ProxyPassReverse    /browser https://127.0.0.1:9980/browser

        # WOPI discovery URL
        ProxyPass           /hosting/discovery https://127.0.0.1:9980/hosting/discovery retry=0
        ProxyPassReverse    /hosting/discovery https://127.0.0.1:9980/hosting/discovery

        # Main websocket
        ProxyPassMatch "/cool/(.*)/ws$" wss://127.0.0.1:9980/cool/$1/ws nocanon

        # Admin Console websocket
        ProxyPass   /cool/adminws wss://127.0.0.1:9980/cool/adminws

        # Download as, Fullscreen presentation and Image upload operations
        ProxyPass           /cool https://127.0.0.1:9980/cool
        ProxyPassReverse    /cool https://127.0.0.1:9980/cool

        # Endpoint with information about availability of various features
        ProxyPass           /hosting/capabilities https://127.0.0.1:9980/hosting/capabilities retry=0
        ProxyPassReverse    /hosting/capabilities https://127.0.0.1:9980/hosting/capabilities
```

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
{"reqId":"uBrnyg1hvOv7TOajkRSD","level":0,"time":"2023-05-10T12:23:32+02:00","remoteAddr":"<IP REMOVED>","user":"--","app":"extract","method":"GET","url":"/ocs/v2.php/cloud/user?format=json","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.24.2","version":"26.0.1.1","data":{"app":"extract"}}
{"reqId":"uBrnyg1hvOv7TOajkRSD","level":3,"time":"2023-05-10T12:23:32+02:00","remoteAddr":"<IP REMOVED>","user":"--","app":"files_sharing","method":"GET","url":"/ocs/v2.php/cloud/user?format=json","message":"/appinfo/app.php is not loaded when \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class is used. Migrate everything from app.php to the Application class.","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.24.2","version":"26.0.1.1","data":{"app":"files_sharing"}}
{"reqId":"yDzC6djBZCM0z35zLlq1","level":0,"time":"2023-05-10T12:23:32+02:00","remoteAddr":"<IP REMOVED>","user":"<USER REMOVED>","app":"extract","method":"GET","url":"/ocs/v2.php/cloud/capabilities?format=json","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.24.2","version":"26.0.1.1","data":{"app":"extract"}}
{"reqId":"yDzC6djBZCM0z35zLlq1","level":3,"time":"2023-05-10T12:23:32+02:00","remoteAddr":"<IP REMOVED>","user":"<USER REMOVED>","app":"files_sharing","method":"GET","url":"/ocs/v2.php/cloud/capabilities?format=json","message":"/appinfo/app.php is not loaded when \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class is used. Migrate everything from app.php to the Application class.","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.24.2","version":"26.0.1.1","data":{"app":"files_sharing"}}
{"reqId":"CrhY0PzVskBrFC1IyG5V","level":0,"time":"2023-05-10T12:23:32+02:00","remoteAddr":"<IP REMOVED>","user":"<USER REMOVED>","app":"extract","method":"GET","url":"/ocs/v2.php/cloud/capabilities?format=json","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.24.2","version":"26.0.1.1","data":{"app":"extract"}}
{"reqId":"CrhY0PzVskBrFC1IyG5V","level":3,"time":"2023-05-10T12:23:32+02:00","remoteAddr":"<IP REMOVED>","user":"<USER REMOVED>","app":"files_sharing","method":"GET","url":"/ocs/v2.php/cloud/capabilities?format=json","message":"/appinfo/app.php is not loaded when \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class is used. Migrate everything from app.php to the Application class.","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.24.2","version":"26.0.1.1","data":{"app":"files_sharing"}}
{"reqId":"Gqby8mCQ92GMOAzx81ac","level":0,"time":"2023-05-10T12:23:32+02:00","remoteAddr":"<IP REMOVED>","user":"--","app":"extract","method":"GET","url":"/ocs/v2.php/apps/user_status/api/v1/predefined_statuses?format=json","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.24.2","version":"26.0.1.1","data":{"app":"extract"}}
{"reqId":"Gqby8mCQ92GMOAzx81ac","level":3,"time":"2023-05-10T12:23:32+02:00","remoteAddr":"<IP REMOVED>","user":"--","app":"files_sharing","method":"GET","url":"/ocs/v2.php/apps/user_status/api/v1/predefined_statuses?format=json","message":"/appinfo/app.php is not loaded when \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class is used. Migrate everything from app.php to the Application class.","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.24.2","version":"26.0.1.1","data":{"app":"files_sharing"}}
{"reqId":"t13wfUjCO65hsu7NviYO","level":0,"time":"2023-05-10T12:23:32+02:00","remoteAddr":"<IP REMOVED>","user":"--","app":"extract","method":"GET","url":"/ocs/v2.php/apps/user_status/api/v1/predefined_statuses?format=json","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.24.2","version":"26.0.1.1","data":{"app":"extract"}}
{"reqId":"t13wfUjCO65hsu7NviYO","level":3,"time":"2023-05-10T12:23:32+02:00","remoteAddr":"<IP REMOVED>","user":"--","app":"files_sharing","method":"GET","url":"/ocs/v2.php/apps/user_status/api/v1/predefined_statuses?format=json","message":"/appinfo/app.php is not loaded when \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class is used. Migrate everything from app.php to the Application class.","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.24.2","version":"26.0.1.1","data":{"app":"files_sharing"}}
{"reqId":"s7cBWRaigR7yXVqZGA5f","level":0,"time":"2023-05-10T12:23:33+02:00","remoteAddr":"<IP REMOVED>","user":"--","app":"extract","method":"GET","url":"/ocs/v2.php/cloud/user?format=json","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.24.2","version":"26.0.1.1","data":{"app":"extract"}}
{"reqId":"s7cBWRaigR7yXVqZGA5f","level":3,"time":"2023-05-10T12:23:33+02:00","remoteAddr":"<IP REMOVED>","user":"--","app":"files_sharing","method":"GET","url":"/ocs/v2.php/cloud/user?format=json","message":"/appinfo/app.php is not loaded when \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class is used. Migrate everything from app.php to the Application class.","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.24.2","version":"26.0.1.1","data":{"app":"files_sharing"}}
{"reqId":"Ep54P5gO0pjxTxWwcXBq","level":0,"time":"2023-05-10T12:23:33+02:00","remoteAddr":"<IP REMOVED>","user":"--","app":"extract","method":"GET","url":"/ocs/v2.php/cloud/user?format=json","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.24.2","version":"26.0.1.1","data":{"app":"extract"}}
{"reqId":"Ep54P5gO0pjxTxWwcXBq","level":3,"time":"2023-05-10T12:23:33+02:00","remoteAddr":"<IP REMOVED>","user":"--","app":"files_sharing","method":"GET","url":"/ocs/v2.php/cloud/user?format=json","message":"/appinfo/app.php is not loaded when \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class is used. Migrate everything from app.php to the Application class.","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.24.2","version":"26.0.1.1","data":{"app":"files_sharing"}}
{"reqId":"hDNsxLGcBKK593tjOrbb","level":3,"time":"2023-05-10T12:23:33+02:00","remoteAddr":"<IP REMOVED>","user":"<USER REMOVED>","app":"files_sharing","method":"PROPFIND","url":"/remote.php/dav/files/<USER REMOVED>/","message":"/appinfo/app.php is not loaded when \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class is used. Migrate everything from app.php to the Application class.","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.24.2","version":"26.0.1.1","data":{"app":"files_sharing"}}
{"reqId":"FPEugHxVhLVdRTlFtGr8","level":3,"time":"2023-05-10T12:23:33+02:00","remoteAddr":"<IP REMOVED>","user":"<USER REMOVED>","app":"files_sharing","method":"PROPFIND","url":"/remote.php/dav/files/<USER REMOVED>/","message":"/appinfo/app.php is not loaded when \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class is used. Migrate everything from app.php to the Application class.","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.24.2","version":"26.0.1.1","data":{"app":"files_sharing"}}
{"reqId":"wrX8xVGzt25eZgTNCSQR","level":0,"time":"2023-05-10T12:23:33+02:00","remoteAddr":"<IP REMOVED>","user":"<USER REMOVED>","app":"extract","method":"GET","url":"/ocs/v2.php/apps/files_sharing/api/v1/shares?path=%2F&reshares=true&subfiles=true","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.24.2","version":"26.0.1.1","data":{"app":"extract"}}
{"reqId":"wrX8xVGzt25eZgTNCSQR","level":3,"time":"2023-05-10T12:23:33+02:00","remoteAddr":"<IP REMOVED>","user":"<USER REMOVED>","app":"files_sharing","method":"GET","url":"/ocs/v2.php/apps/files_sharing/api/v1/shares?path=%2F&reshares=true&subfiles=true","message":"/appinfo/app.php is not loaded when \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class is used. Migrate everything from app.php to the Application class.","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.24.2","version":"26.0.1.1","data":{"app":"files_sharing"}}
{"reqId":"aropd0mX2NV3iWyRKC2l","level":0,"time":"2023-05-10T12:23:33+02:00","remoteAddr":"<IP REMOVED>","user":"<USER REMOVED>","app":"extract","method":"GET","url":"/ocs/v2.php/apps/files_sharing/api/v1/shares?path=%2F&reshares=true&subfiles=true","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.24.2","version":"26.0.1.1","data":{"app":"extract"}}
{"reqId":"aropd0mX2NV3iWyRKC2l","level":3,"time":"2023-05-10T12:23:33+02:00","remoteAddr":"<IP REMOVED>","user":"<USER REMOVED>","app":"files_sharing","method":"GET","url":"/ocs/v2.php/apps/files_sharing/api/v1/shares?path=%2F&reshares=true&subfiles=true","message":"/appinfo/app.php is not loaded when \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class is used. Migrate everything from app.php to the Application class.","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.24.2","version":"26.0.1.1","data":{"app":"files_sharing"}}
{"reqId":"v5CzLO0Yyu61jM61lKOP","level":3,"time":"2023-05-10T12:23:44+02:00","remoteAddr":"<IP REMOVED>","user":"<USER REMOVED>","app":"files_sharing","method":"PROPFIND","url":"/remote.php/dav/files/<USER REMOVED>/PN%209999%20Example/","message":"/appinfo/app.php is not loaded when \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class is used. Migrate everything from app.php to the Application class.","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.24.2","version":"26.0.1.1","data":{"app":"files_sharing"}}
{"reqId":"dteMhiMZRlE2V21iWXdl","level":0,"time":"2023-05-10T12:23:44+02:00","remoteAddr":"<IP REMOVED>","user":"<USER REMOVED>","app":"extract","method":"GET","url":"/ocs/v2.php/apps/files_sharing/api/v1/shares?path=%2FPN+9999+Example%2F&reshares=true&subfiles=true","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.24.2","version":"26.0.1.1","data":{"app":"extract"}}
{"reqId":"dteMhiMZRlE2V21iWXdl","level":3,"time":"2023-05-10T12:23:44+02:00","remoteAddr":"<IP REMOVED>","user":"<USER REMOVED>","app":"files_sharing","method":"GET","url":"/ocs/v2.php/apps/files_sharing/api/v1/shares?path=%2FPN+9999+Example%2F&reshares=true&subfiles=true","message":"/appinfo/app.php is not loaded when \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class is used. Migrate everything from app.php to the Application class.","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.24.2","version":"26.0.1.1","data":{"app":"files_sharing"}}
{"reqId":"HKSTXXJD0CYkifrs6Epi","level":0,"time":"2023-05-10T12:23:47+02:00","remoteAddr":"<IP REMOVED>","user":"<USER REMOVED>","app":"extract","method":"POST","url":"/ocs/v2.php/apps/richdocuments/api/v1/document?format=json","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.24.2","version":"26.0.1.1","data":{"app":"extract"}}
{"reqId":"HKSTXXJD0CYkifrs6Epi","level":3,"time":"2023-05-10T12:23:47+02:00","remoteAddr":"<IP REMOVED>","user":"<USER REMOVED>","app":"files_sharing","method":"POST","url":"/ocs/v2.php/apps/richdocuments/api/v1/document?format=json","message":"/appinfo/app.php is not loaded when \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class is used. Migrate everything from app.php to the Application class.","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.24.2","version":"26.0.1.1","data":{"app":"files_sharing"}}
{"reqId":"1nETLiretlx5a9WUrvHv","level":0,"time":"2023-05-10T12:23:47+02:00","remoteAddr":"<IP REMOVED>","user":"--","app":"extract","method":"GET","url":"/ocs/v2.php/cloud/user?format=json","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.24.2","version":"26.0.1.1","data":{"app":"extract"}}
{"reqId":"1nETLiretlx5a9WUrvHv","level":3,"time":"2023-05-10T12:23:47+02:00","remoteAddr":"<IP REMOVED>","user":"--","app":"files_sharing","method":"GET","url":"/ocs/v2.php/cloud/user?format=json","message":"/appinfo/app.php is not loaded when \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class is used. Migrate everything from app.php to the Application class.","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.24.2","version":"26.0.1.1","data":{"app":"files_sharing"}}
{"reqId":"68VEa7xHrZetiSk2cLnF","level":3,"time":"2023-05-10T12:23:47+02:00","remoteAddr":"<IP REMOVED>","user":"--","app":"files_sharing","method":"GET","url":"/apps/richdocuments/direct/oncMwT2OFiQk5DnilswMWeMjccA4KsE2J6W64q6s5m6f8wzqbg25uA9QjsidBk5q","message":"/appinfo/app.php is not loaded when \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class is used. Migrate everything from app.php to the Application class.","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.24.2","version":"26.0.1.1","data":{"app":"files_sharing"}}
{"reqId":"68VEa7xHrZetiSk2cLnF","level":0,"time":"2023-05-10T12:23:47+02:00","remoteAddr":"<IP REMOVED>","user":"--","app":"extract","method":"GET","url":"/apps/richdocuments/direct/oncMwT2OFiQk5DnilswMWeMjccA4KsE2J6W64q6s5m6f8wzqbg25uA9QjsidBk5q","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.24.2","version":"26.0.1.1","data":{"app":"extract"}}
{"reqId":"68VEa7xHrZetiSk2cLnF","level":4,"time":"2023-05-10T12:23:47+02:00","remoteAddr":"<IP REMOVED>","user":"--","app":"richdocuments","method":"GET","url":"/apps/richdocuments/direct/oncMwT2OFiQk5DnilswMWeMjccA4KsE2J6W64q6s5m6f8wzqbg25uA9QjsidBk5q","message":"Failed to generate token for existing file on direct editing","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.24.2","version":"26.0.1.1","data":{"exception":"{\"class\":\"OCP\\Files\\NotPermittedException\",\"message\":\"\",\"code\":0,\"file\":\"/opt/nextcloud-26.0.1/apps/richdocuments/lib/TokenManager.php:187\",\"trace\":\"#0 /opt/nextcloud-26.0.1/apps/richdocuments/lib/Controller/DirectViewController.php(160): OCA\\Richdocuments\\TokenManager->getToken()\\n#1 /opt/nextcloud-26.0.1/lib/private/AppFramework/Http/Dispatcher.php(230): OCA\\Richdocuments\\Controller\\DirectViewController->show()\\n#2 /opt/nextcloud-26.0.1/lib/private/AppFramework/Http/Dispatcher.php(137): OC\\AppFramework\\Http\\Dispatcher->executeController()\\n#3 /opt/nextcloud-26.0.1/lib/private/AppFramework/App.php(183): OC\\AppFramework\\Http\\Dispatcher->dispatch()\\n#4 /opt/nextcloud-26.0.1/lib/private/Route/Router.php(315): OC\\AppFramework\\App::main()\\n#5 /opt/nextcloud-26.0.1/lib/base.php(1056): OC\\Route\\Router->match()\\n#6 /opt/nextcloud-26.0.1/index.php(36): OC::handleRequest()\\n#7 {main}\"}","app":"richdocuments"}}
{"reqId":"uTaUp3blwtDSKrsydj8s","level":3,"time":"2023-05-10T12:23:48+02:00","remoteAddr":"<IP REMOVED>","user":"--","app":"files_sharing","method":"GET","url":"/core/js/oc.js?v=3fdca2e8","message":"/appinfo/app.php is not loaded when \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class is used. Migrate everything from app.php to the Application class.","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.24.2","version":"26.0.1.1","data":{"app":"files_sharing"}}
{"reqId":"uTaUp3blwtDSKrsydj8s","level":0,"time":"2023-05-10T12:23:48+02:00","remoteAddr":"<IP REMOVED>","user":"--","app":"extract","method":"GET","url":"/core/js/oc.js?v=3fdca2e8","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.24.2","version":"26.0.1.1","data":{"app":"extract"}}
```

Collabora log gathered using docker log doesn't include any relevant information.

Apache Error log doesn't include any relevant information.

</details>

**Comment by mnheia** [comment]
Closing as duplicate of #2681
