### ISSUE TITLE
Document language in new documents does not respect language settings

### ISSUE THREAD

**Issue by bpcurse** [nextcloud/richdocuments#496]
**Describe the bug**
When a new document is created, the document language is always set to English (USA), although language and locale are set to German (informal) and Germany.

- The document language can be set to German in the menu and is correctly preserved when the document is closed and reopened.

- Choosing the "Reset to default language" option in the menu seems to have no effect, neither when English is the current document language, nor when German is. The command seems to be ignored.

**Expected behavior**
Collabora should respect the language settings when new documents are created.

**Screenshots**
![Bildschirmfoto_2019-05-09_22-07-39](https://user-images.githubusercontent.com/29312856/57483427-5c41fc80-7296-11e9-9d56-da3d95b885bf.png)
![Bildschirmfoto_2019-05-09_22-08-25](https://user-images.githubusercontent.com/29312856/57483431-5ea45680-7296-11e9-99af-15a17127cddb.png)

**Client details:**
 - OS: Linux
 - Browser Firefox
 - Version 66.0.4
 - Device: Desktop

## Server details

**Operating system**:
Shared Webhosting

**Web server:**
Apache

**Database:**
MySQL 5.7.25

**PHP version:**
7.2.13

**Nextcloud version:**
15.0.5

**Version of the richdocuments app**
3.3.2

**Version of Collabora Online**
CODE 4.0.1-1

**Comment by filipkemuel** [comment]
I'm having the same exact issue. Except all new documents are in German instead of Danish.  I can change the language to Danish after making it. But new documents are always in German. And with spreadsheets also the table names start out in German so that I have to manually change them.

I found an old thread talking about replacing template documents in ```/var/www/nextcloud/core/templates/filetemplates``` but that no longer seems to make a difference.

### Client details

**OS:** Arch Linux
**Browser:** Firefox 66.0.5

### Server details

**Operating system:**
Ubuntu 18.04.2

**Web server:**
Nginx

**Database:**
MariaDB 10.1.38

**PHP version:**
7.2.17

**Nextcloud:**
Version 16.0.0

**richdocuments app:**
Version 3.3.2

**Collabora Online:**
Running via docker and has [-e "dictionaries=da en de"] to enable Danish dictionaries.

LOOLWSD: 4.0.4 (git hash: 305832f)
LOKit: Collabora Office 6.0-29 (git hash: 5a695a1)

**Comment by thebearon** [comment]
This is because of the locale of the templates shipped with the installation. You can specify your own templates in the settings as a workaround.

Eventually this should be fixed in a way that at least empty files can be generated based on user language/locale. It will likely require modifications both in Collabora Online and in richdocuments.

**Comment by kromsam** [comment]
> This is because of the locale of the templates shipped with the installation. You can specify your own templates in the settings as a workaround.
> 
> Eventually this should be fixed in a way that at least empty files can be generated based on user language/locale. It will likely require modifications both in Collabora Online and in richdocuments.

@thebearon I did not see the option to change the templates in the settings. Is it shipped in an update?

I also opened a topic in the Nextcloud Community Support forum. https://help.nextcloud.com/t/how-do-i-change-the-default-language-in-collabora/53667

**Comment by zeigerpuppy** [comment]
this still seems to be an issue.
Is there a way to manually set the templates?  Or does the Collabora docker container need to be started with a different environmental option?

The per-server and per-user templates option would be the best way to solve this.

**Comment by juliushaertl** [comment]
It is currently not possible to change the empty templates, but I guess that would be the best option to avoid issues with the shipped ones.

@thebearon The shipped templates don't have any language/locale set, how is the language determined then in collabora?

**Comment by MollyBe** [comment]
@zeigerpuppy It is somewhat possible to change the default templates, see [here](https://help.nextcloud.com/t/how-do-i-change-the-default-language-in-collabora/53667).

Onlyoffice has language default to the personal language of each user.

**Comment by infidelus** [comment]
Doesn't seem to work.  I created template files of each type and copied them into the folder in empty_templates folder in ncdata but every file opened still defaults to German.

**Comment by manu-p** [comment]
Same on my side... So no way to force a default language in the templates provided other than those already setup?

Alternatively, since it's possible to upload your owns, is there a way to remove the "empty" ones as provided during installation (I guess)?

**Comment by juliushaertl** [comment]
@thebearon I was thinking if we could somehow change the language that is used in the empty template files on the fly? Do you have any hint where the language is set in those templates?

**Comment by timar** [comment]
> @thebearon I was thinking if we could somehow change the language that is used in the empty template files on the fly? Do you have any hint where the language is set in those templates?

You can create language agnostic template files, and the language will be set to the UI language. See e.g. https://cgit.freedesktop.org/libreoffice/online/commit/?id=a66083de9b35034c79fae29b4a1c08a0fc2682de

**Comment by thebearon** [comment]
This should be fine after fb68779048bdeedc1cbf87d2d992b966b9b0c3b1.

**Comment by DanScharon** [comment]
@thebearon cannot confirm, seeing this still with richdocuments 3.7.11

**Comment by juliushaertl** [comment]
Make sure to run `occ richdocuments:update-empty-templates` to get the latest empty templates into your system.

**Comment by infidelus** [comment]
Just tried the occ command and got:

`sudo -u www-data php /var/www/nextcloud/occ richdocuments:update-empty-templates
Empty template files were updated
An unhandled exception has been thrown:
TypeError: Return value of "OCA\RichDocuments\Command\UpdateEmptyTemplates::execute()" must be of the type int, "null" returned. in /var/www/nextcloud/apps/mail/vendor/symfony/console/Command/Command.php:261
Stack trace:
#0 /var/www/nextcloud/apps/mail/vendor/symfony/console/Application.php(920): Symfony\Component\Console\Command\Command->run()
#1 /var/www/nextcloud/apps/mail/vendor/symfony/console/Application.php(266): Symfony\Component\Console\Application->doRunCommand()
#2 /var/www/nextcloud/apps/mail/vendor/symfony/console/Application.php(142): Symfony\Component\Console\Application->doRun()
#3 /var/www/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run()
#4 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
#5 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
`

**Comment by juliushaertl** [comment]
That is actually a mail issue: https://github.com/nextcloud/mail/issues/4102

**Comment by DanScharon** [comment]
> Make sure to run `occ richdocuments:update-empty-templates` to get the latest empty templates into your system.

thank you, that did the trick!

**Comment by jonas2515** [comment]
It seems that this broke again. I'm seeing default language set to english even when using the up-to-date empty templates. 

Checking with the original files from https://github.com/nextcloud/richdocuments/commit/fb68779048bdeedc1cbf87d2d992b966b9b0c3b1, language gets set correctly, so the template regressed and is now setting a language again.

**Comment by DanScharon** [comment]
can confirm, the latest template is unfortunately setting a language again
